# Generated by Django 4.0.4 on 2022-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp_posts', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
