# Generated by Django 4.0.4 on 2022-04-29 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='date checked in'),
        ),
        migrations.AddField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='checked-out'),
        ),
        migrations.AddField(
            model_name='book',
            name='checked_out_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date checked-out'),
        ),
    ]
