# Generated by Django 4.0.4 on 2022-05-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_checked_out_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_by', models.CharField(max_length=50)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_app.book')),
            ],
        ),
    ]
