# Generated by Django 4.0.4 on 2022-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='book_title',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checked_in_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checked_out_date',
        ),
        migrations.AddField(
            model_name='checkout',
            name='checked_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='date checked in'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='checked_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='date checked-out'),
        ),
    ]
