# Generated by Django 4.0.4 on 2022-05-06 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 6, 18, 35, 48, 504733, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chirps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
