# Generated by Django 4.0.4 on 2022-05-06 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 5, 28, 117321, tzinfo=utc)),
        ),
    ]
