# Generated by Django 3.2.13 on 2022-04-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('completed_date', models.CharField(max_length=200)),
                ('iteam_boolean', models.BooleanField(max_length=200)),
            ],
        ),
    ]
