# Generated by Django 3.2.13 on 2022-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220429_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='completed_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='item_boolean',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
