# Generated by Django 4.0.4 on 2022-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionfacts',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
