# Generated by Django 4.0.4 on 2022-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_chirps_chirp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='text',
            field=models.TextField(default='', max_length=128),
        ),
    ]
