# Generated by Django 4.0.4 on 2022-05-04 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_list', '0005_groceryitem_user_alter_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grocery_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
