# Generated by Django 4.0.4 on 2022-04-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
