# Generated by Django 4.0.4 on 2022-06-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryPrompts',
            new_name='StoryPrompt',
        ),
    ]
