# Generated by Django 4.0.4 on 2022-06-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0002_rename_storyprompts_storyprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
