# Generated by Django 4.0.4 on 2022-06-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0003_alter_story_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('user_options', models.CharField(max_length=200)),
                ('enemy_tile', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tiles', to='storied.story')),
            ],
        ),
        migrations.DeleteModel(
            name='StoryPrompt',
        ),
    ]
