# Generated by Django 4.0.4 on 2022-06-02 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0004_storytile_delete_storyprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytile',
            name='x_coord',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='storytile',
            name='y_coord',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storytile',
            name='user_options',
            field=models.CharField(blank=True, choices=[('FW', 'Forward'), ('BW', 'Backward'), ('LF', 'Left'), ('RT', 'Right'), ('AT', 'Attack'), ('PU', 'Pick-up')], max_length=2, null=True),
        ),
    ]
