# Generated by Django 4.0.4 on 2022-06-02 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0005_storytile_x_coord_storytile_y_coord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='play_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
