# Generated by Django 4.0.4 on 2022-06-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storied', '0007_useroptions_userplayer_remove_storytile_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlayer',
            new_name='CharacterPlayer',
        ),
    ]
