# Economic Indicator Series search terms Output

from texttable import Texttable

economic_indicator_series = [
    ['INDICATOR DESCRIPTION', 'SERIES'],
    ['US Treasuries Held by the Fed', 'TREAST'],
    ['Mortgage Backed Sec Held by the Fed', 'MBST'],
    ['All Fed Reserve Banks - Total Assets', 'WALCL'],
    ['All Commercial Banks - Total Assets', 'TLAAC'],
    ['Number of US Banks', 'BOPBCA'],
    ['Number of US Commercial Banks', 'USNUM'],
    ['Equity/Asset Ratio', 'EQTA'],
    ['Bank Credit of All Commercial Banks', 'TOTBKCR'],
    ['Securitized Total Consumer Loans', 'TOTALSEC'],
    ['Total Consumer Credit Outstanding', 'TOTALSL'],
    ['Total Investments All Commercial Banks', 'INVEST'],
    ['US Gov\'t Securities at All Com. Banks', 'USGSEC'],
    ['Total Consumer Loans', 'CONSUMER'],
    ['Total Commercial/Industrial Loans', 'BUSLOANS'],
    ['Delinquencies On All Loans And Leases', 'DALLCACBEP'],
    ['US 10-YR / 2-YR Spread', 'T10Y2Y'],
    ['3-Month T-Bill: Secondary Market Rate', 'TB3MS'],
    ['10-Yr Treasury Const. Maturity Rate', 'DGS10'],
    ['Federal Government Debt (Public)', 'GFDEBTN'],
    ['Interest on National Debt', 'FYOINT'],
    ['Federal Spending', 'FYONET'],
    ['Federal Receipts', 'FYFR'],
    ['Budget Deficit/Surplus', 'FYFSD'],
    ['Consumer Debt/Income Ratio', 'CDSP'],
    ['New Home Permits', 'PERMIT'],
    ['New Home Sales', 'HSN1F'],
    ['Outstanding Mortgage Debt', 'CMDEBT'],
    ['Manufacturers\' New Orders', 'DGORDER'],
    ['Capacity Utilization: Total Industry', 'TCU'],
    ['Total Construction Spending', 'TTLCONS'],
    ['Total Business Inventories', 'BUSINV'],
    ['Light Weight Vehicle Sales', 'ALTSALES'],
    ['Univ of Michigan: Consumer Sentiment', 'UMCSENT'],
    ['St. Louis Financial Stress Index', 'STLFSI'],
    ['Spot Oil Price - West Texas Intermediate', 'OILPRICE'],
    ['Consumer Price Index: Seasonally Adj.', 'CPIAUCSL'],
    ['Civilian Total Unemployment Rate', 'UNRATE'],
    ['Long Term Unemployment: >27 WKS', 'UEMP27OV'],
    ['Length of Unemployment', 'UEMPMED'],
    ['Total US Workforce', 'CE16OV'],
    ['US Employment/Population Ratio', 'EMRATIO'],
    ['US Population', 'POP'],
    ['Avg Hourly Earnings: Manufacturing',  'AHEMAN'],
    ['Avg Weekly Hours: Manufacturing', 'AWHMAN'],
    ['Avg Weekly OT Hours: Manufacturing', 'AWOTMAN'],
    ['USD/GBP Currency Exchange Rate', 'DEXUSUK'],
    ['USD/EUR Currency Exchange Rate', 'DEXUSEU'],
    ['JPN/USD Currency Exchange Rate', 'DEXJPUS'],
    ['MXP/USD Currency Exchange Rate', 'DEXMXUS'],
    ['CAD/USD Currency Exchange Rate', 'DEXCAUS'],
    ['CNY/USD Currency Exchange Rate', 'DEXCHUS'],
    ['Commercial Paper Outstanding', 'COMPOUT'],
    ['CBOE Volatility Index', 'VIXCLS'],
    ['US Gross Domestic Product', 'GDP'],
    ['US Gross National Product', 'GNP'],
    ['US Current Account Balance', 'NETFI'],
    ['US Exports Goods & Services',	'EXPGS'],
    ['US Imports Goods & Services', 'IMPGS'],
    ['Fed Govt: Defense Budget', 'DGI'],
    ['Fed Govt: Tax Receipts', 'FGRECPT'],
    ['Fed Govt: Budget Deficit', 'TGDEF'],
    ['Corporate Profits After Tax', 'CP'],
    ['Corporate Dividends', 'DIVIDEND'],
    ['Personal Income', 'PI'],
    ['Personal Savings', 'PSAVE'],
    ['Personal Savings Rate', 'PSAVERT'],
    ['30-yr Conventional Mortgage Rate', 'MORTGAGE30US'],
    ['Discount Rate', 'DPCREDIT'],
    ['Effective Federal Funds Rate', 'FEDFUNDS'],
    ['Production of Total Industry in Greece', 'GRCPROINDMISMEI'],
    ['Total Retail Trade in Greece', 'GRCSARTMISMEI'],
    ['Unemployment Rate - Greece', 'GRCURHARMMDSMEI'],
    ['M1 Money Supply', 'M1'],
    ['M2 Money Supply', 'M2'],
    ['MZM Money Supply', 'MZM'],
    ['Velocity of M1 Money Stock', 'M1V'],
    ['Velocity of M2 Money Stock', 'M2V'],
    ['Velocity of MZM Money Stock', 'MZMV'],
    ['M1 Money Multiplier', 'MULT'],
    ['Producer Price Index: All Commodities', 'PPIACO'],
    ['Imports from China', 'IMPCH'],
    ['Imports from Japan', 'IMPJP'],
    ['Imports from Mexico', 'IMPMX'],
    ['Imports from Canada', 'IMPCA'],
    ['Imports from Germany', 'IMPGE'],
    ['Imports from UK', 'IMPUK'],
    ['Exports to China', 'EXPCH'],
    ['Exports to Japan', 'EXPJP'],
    ['Exports to Mexico', 'EXPMX'],
    ['Exports to Canada', 'EXPCA'],
    ['Exports to Germany', 'EXPGE'],
    ['Exports to UK', 'EXPUK'],
    ['Exports: Goods', 'BOPGEXP'],
    ['Imports: Goods', 'BOPGIMP'],
    ['Balance: Goods', 'BOPGTB'],
    ['Exports: Services', 'BOPGSXP'],
    ['Imports: Services', 'BOPSIMP'],
    ['Balance: Services', 'BOPSTB'],
    ['Balance: Goods & Services', 'BOPGSTB'],
    ['All Employees, Total Nonfarm', 'PAYEMS']]

def display_series():
    t = Texttable()
    t.add_rows(economic_indicator_series)
    print(t.draw())

# print(tabulate((economic_indicator_series), headers=['Economic Indicator', 'Series'], tablefmt='orgtbl'))
'''
import datetime
import pandas_datareader.data as web

start = datetime.date (2020, 1, 1)
end = datetime.date (2022, 3, 1)
stock_ticker = input('Enter the stock ticker: ').upper()
df_stk = web.DataReader(stock_ticker, 'yahoo', start, end)#['Adj Close']
print(df_stk)
'''
