# Stock and Ticker output

from tabulate import tabulate

companies_tickers = [
    ['APPLE INC.', 'AAPL'],
    ['MICROSOFT CORPORATION', 'MSFT'],
    ['ALPHABET INC.', 'GOOG'],
    ['AMAZON.COM, INC.', 'AMZN'],
    ['TESLA, INC.', 'TSLA'],
    ['BERKSHIRE HATHAWAY INC.', 'BRK.A'],
    ['NVIDIA CORPORATION', 'NVDA'],
    ['Meta Platforms, Inc. - facebook', 'FB'],
    ['UNITEDHEALTH GROUP INCORPORATED', 'UNH'],
    ['VISA INC.', 'V'],
    ['JOHNSON & JOHNSON', 'JNJ'],
    ['WALMART INC.', 'WMT'],
    ['JPMORGAN CHASE & CO.', 'JPM'],
    ['THE PROCTER & GAMBLE COMPANY', 'PG'],
    ['MASTERCARD INCORPORATED.', 'MA'],
    ['EXXON MOBIL CORPORATION', 'XOM'],
    ['BANK OF AMERICA CORPORATION', 'BAC'],
    ['CHEVRON CORPORATION', 'CVX'],
    ['THE HOME DEPOT, INC.', 'HD'],
    ['PFIZER INC.', 'PFE'],
    ['ABBVIE INC.', 'ABBV'],
    ['ELI LILLY AND COMPANY', 'LLY'],
    ['THE COCA-COLA COMPANY',	'KO'],
    ['Broadcom Inc.', 'AVGO'],
    ['COSTCO WHOLESALE CORPORATION', 'COST'],
    ['THE WALT DISNEY COMPANY', 'DIS'],
    ['PEPSICO, INC.', 'PEP'],
    ['THERMO FISHER SCIENTIFIC INC.', 'TMO'],
    ['CISCO SYSTEMS, INC.', 'CSCO'],
    ['ACCENTURE PUBLIC LIMITED COMPANY', 'ACN'],
    ['VERIZON COMMUNICATIONS INC.', 'VZ'],
    ['ORACLE CORPORATION', 'ORCL'],
    ['ADOBE INC.', 'ADBE'],
    ['COMCAST CORPORATION', 'CMCSA'],
    ['NIKE, INC.', 'NKE'],
    ['MERCK & CO., INC.', 'MRK'],
    ['SALESFORCE.COM, INC.', 'CRM'],
    ['ABBOTT LABORATORIES',	'ABT'],
    ['DANAHER CORPORATION', 'DHR'],
    ['INTEL CORPORATION', 'INTC'],
    ['MCDONALD\'S CORPORATION', 'MCD'],
    ['WELLS FARGO & COMPANY', 'WFC'],
    ['UNITED PARCEL SERVICE, INC.', 'UPS'],
    ['ADVANCED MICRO DEVICES, INC.', 'AMD'],
    ['AT&T INC.', 'T'],
    ['NEXTERA ENERGY, INC.', 'NEE'],
    ['TEXAS INSTRUMENTS INCORPORATED', 'TXN'],
    ['NETFLIX, INC.', 'NFLX'],
    ['QUALCOMM INCORPORATED', 'QCOM'],
    ['LINDE PUBLIC LIMITED COMPANY', 'LIN']]

def display_stock_tickers():
    print(tabulate((companies_tickers), headers=['Company', 'Stock Ticker'], tablefmt='orgtbl'))