# Generated by Django 4.0.4 on 2022-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'verbose_name_plural': 'Groceries'},
        ),
        migrations.AlterField(
            model_name='grocery',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
