# Generated by Django 4.0.4 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_alter_grocery_options_alter_grocery_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
