# Generated by Django 4.0.4 on 2022-05-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'ToDos'},
        ),
    ]
