# Generated by Django 4.0.4 on 2022-04-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_thrones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='game_of_thrones.house'),
        ),
    ]
