# Generated by Django 4.0.4 on 2022-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_thrones', '0002_alter_character_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='jon-snow'),
            preserve_default=False,
        ),
    ]
