# Generated by Django 4.0.4 on 2022-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_of_thrones', '0005_character_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enemies',
            field=models.ManyToManyField(related_name='enemy_characters', to='game_of_thrones.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='friends',
            field=models.ManyToManyField(related_name='friendly_characters', to='game_of_thrones.character'),
        ),
    ]
