# Generated by Django 4.1.dev20220422170756 on 2022-04-28 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
