# Generated by Django 4.1.dev20220422170756 on 2022-04-28 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 28, 23, 20, 32, 221196, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
