# Generated by Django 4.1.dev20220422170756 on 2022-04-29 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_alter_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 17, 49, 26, 787739, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
