# Generated by Django 4.0.4 on 2022-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
