# Generated by Django 4.0.4 on 2022-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_alter_groceryitem_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='check_completed',
            field=models.BooleanField(default=False),
        ),
    ]
