# Generated by Django 4.0.4 on 2022-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChirpPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('post_text', models.CharField(max_length=128)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
