# Generated by Django 4.0.4 on 2022-05-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirppost',
            name='date_edited',
        ),
    ]
