# Generated by Django 4.0.4 on 2022-05-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0004_remove_chirppost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirppost',
            old_name='user',
            new_name='author',
        ),
    ]
