# Generated by Django 4.0.4 on 2022-05-09 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirp', '0005_rename_user_chirppost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirppost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chirps', to=settings.AUTH_USER_MODEL),
        ),
    ]
