# Generated by Django 4.0.4 on 2022-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateField()),
                ('last_name', models.CharField(max_length=200)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
