# Generated by Django 4.0.4 on 2022-04-27 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'verbose_name_plural': 'Groceries'},
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='last_name',
        ),
        migrations.AddField(
            model_name='grocery',
            name='completed_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 17, 25, 48, 81486, tzinfo=utc)),
        ),
    ]
