# Generated by Django 4.0.4 on 2022-04-28 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0007_alter_grocery_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 16, 54, 19, 65529, tzinfo=utc)),
        ),
    ]
