# Generated by Django 4.0.4 on 2022-04-28 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0008_alter_grocery_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 16, 55, 54, 765011, tzinfo=utc)),
        ),
    ]
