# Generated by Django 4.0.4 on 2022-04-28 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0009_alter_grocery_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='completed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 17, 20, 7, 447510, tzinfo=utc)),
        ),
    ]
