# Generated by Django 4.0.4 on 2022-04-28 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0011_alter_grocery_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 17, 24, 22, 943978, tzinfo=utc)),
        ),
    ]
