# Generated by Django 4.0.4 on 2022-05-06 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirppost',
            name='date',
        ),
        migrations.AddField(
            model_name='chirppost',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chirppost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chirp_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
