# Generated by Django 4.0.4 on 2022-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=128)),
                ('posted_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
