# Generated by Django 4.0.4 on 2022-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='posted_message',
        ),
    ]
