# Generated by Django 4.0.4 on 2022-05-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_users_alter_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='author',
            new_name='user_name',
        ),
    ]
