# Generated by Django 4.0.4 on 2022-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_groceryitem_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
    ]
